-- Privacy-conscious administrator insights.
-- Stores coarse product usage only: no child records, request bodies, search
-- text, raw IP addresses, or full referrer URLs are retained.

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS membership_status TEXT NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS membership_cancelled_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS membership_cancelled_reason TEXT;

ALTER TABLE public.users DROP CONSTRAINT IF EXISTS users_membership_status_check;
ALTER TABLE public.users ADD CONSTRAINT users_membership_status_check
  CHECK (membership_status IN ('active', 'cancelled'));

CREATE TABLE IF NOT EXISTS public.parent_activity_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  feature TEXT NOT NULL,
  action TEXT NOT NULL,
  route_template TEXT NOT NULL,
  outcome TEXT NOT NULL DEFAULT 'success' CHECK (outcome IN ('success', 'client_error', 'server_error')),
  response_status INTEGER NOT NULL DEFAULT 200 CHECK (response_status BETWEEN 100 AND 599),
  duration_ms INTEGER CHECK (duration_ms IS NULL OR duration_ms BETWEEN 0 AND 120000),
  occurred_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.parent_activity_events
  ADD COLUMN IF NOT EXISTS outcome TEXT NOT NULL DEFAULT 'success',
  ADD COLUMN IF NOT EXISTS response_status INTEGER NOT NULL DEFAULT 200,
  ADD COLUMN IF NOT EXISTS duration_ms INTEGER;
ALTER TABLE public.parent_activity_events DROP CONSTRAINT IF EXISTS parent_activity_events_outcome_check;
ALTER TABLE public.parent_activity_events ADD CONSTRAINT parent_activity_events_outcome_check
  CHECK (outcome IN ('success', 'client_error', 'server_error'));
ALTER TABLE public.parent_activity_events DROP CONSTRAINT IF EXISTS parent_activity_events_response_status_check;
ALTER TABLE public.parent_activity_events ADD CONSTRAINT parent_activity_events_response_status_check
  CHECK (response_status BETWEEN 100 AND 599);
ALTER TABLE public.parent_activity_events DROP CONSTRAINT IF EXISTS parent_activity_events_duration_ms_check;
ALTER TABLE public.parent_activity_events ADD CONSTRAINT parent_activity_events_duration_ms_check
  CHECK (duration_ms IS NULL OR duration_ms BETWEEN 0 AND 120000);

CREATE INDEX IF NOT EXISTS parent_activity_events_user_date_idx
  ON public.parent_activity_events(user_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS parent_activity_events_feature_date_idx
  ON public.parent_activity_events(feature, occurred_at DESC);
CREATE INDEX IF NOT EXISTS parent_activity_events_journey_idx
  ON public.parent_activity_events(route_template, action, occurred_at DESC);
CREATE INDEX IF NOT EXISTS parent_activity_events_outcome_date_idx
  ON public.parent_activity_events(outcome, occurred_at DESC);

CREATE TABLE IF NOT EXISTS public.site_analytics_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_hash TEXT NOT NULL,
  page_path TEXT NOT NULL,
  feature TEXT NOT NULL,
  country_code TEXT,
  region_code TEXT,
  referrer_domain TEXT,
  device_category TEXT NOT NULL DEFAULT 'unknown',
  visit_hour TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT date_trunc('hour', now()),
  visited_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Older copies used one record per page and session for an entire day. An
-- hourly bucket gives a more useful visit count without recording every click.
ALTER TABLE public.site_analytics_events
  ADD COLUMN IF NOT EXISTS visit_hour TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT date_trunc('hour', now());
DROP INDEX IF EXISTS site_analytics_events_session_page_day_unique;
CREATE UNIQUE INDEX IF NOT EXISTS site_analytics_events_session_page_hour_unique
  ON public.site_analytics_events(visitor_hash, page_path, visit_hour);

CREATE INDEX IF NOT EXISTS site_analytics_events_date_idx
  ON public.site_analytics_events(visited_at DESC);
CREATE INDEX IF NOT EXISTS site_analytics_events_feature_date_idx
  ON public.site_analytics_events(feature, visited_at DESC);
CREATE INDEX IF NOT EXISTS site_analytics_events_visitor_date_idx
  ON public.site_analytics_events(visitor_hash, visited_at DESC);

CREATE TABLE IF NOT EXISTS public.admin_audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  target_user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  action TEXT NOT NULL CHECK (action IN ('admin_granted', 'admin_removed', 'membership_cancelled', 'membership_reactivated')),
  reason TEXT,
  occurred_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS admin_audit_events_target_date_idx
  ON public.admin_audit_events(target_user_id, occurred_at DESC);

-- Raw analytics are temporary. Daily summaries contain totals only and retain
-- no user IDs, visitor hashes, routes, referrers, regions, or response codes.
CREATE TABLE IF NOT EXISTS public.analytics_retention_settings (
  id BOOLEAN PRIMARY KEY DEFAULT true CHECK (id = true),
  raw_retention_days INTEGER NOT NULL DEFAULT 90 CHECK (raw_retention_days BETWEEN 30 AND 365),
  summary_retention_months INTEGER NOT NULL DEFAULT 36 CHECK (summary_retention_months BETWEEN 12 AND 60),
  last_maintenance_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
INSERT INTO public.analytics_retention_settings (id) VALUES (true) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.analytics_daily_summaries (
  summary_date DATE NOT NULL,
  source TEXT NOT NULL CHECK (source IN ('parent', 'site')),
  feature TEXT NOT NULL,
  total_count INTEGER NOT NULL DEFAULT 0,
  unique_count INTEGER NOT NULL DEFAULT 0,
  success_count INTEGER NOT NULL DEFAULT 0,
  client_error_count INTEGER NOT NULL DEFAULT 0,
  server_error_count INTEGER NOT NULL DEFAULT 0,
  average_duration_ms INTEGER,
  PRIMARY KEY (summary_date, source, feature)
);
CREATE INDEX IF NOT EXISTS analytics_daily_summaries_date_idx
  ON public.analytics_daily_summaries(summary_date DESC);

CREATE OR REPLACE FUNCTION public.rollup_and_prune_admin_analytics()
RETURNS TABLE (parent_events_removed BIGINT, site_events_removed BIGINT, summaries_kept BIGINT) AS $$
DECLARE
  raw_days INTEGER;
  summary_months INTEGER;
  parent_removed BIGINT;
  site_removed BIGINT;
  summary_total BIGINT;
BEGIN
  SELECT raw_retention_days, summary_retention_months INTO raw_days, summary_months
  FROM public.analytics_retention_settings WHERE id = true;

  INSERT INTO public.analytics_daily_summaries (summary_date, source, feature, total_count, unique_count, success_count, client_error_count, server_error_count, average_duration_ms)
  SELECT occurred_at::date, 'parent', feature, COUNT(*)::integer, COUNT(DISTINCT user_id)::integer,
    COUNT(*) FILTER (WHERE outcome = 'success')::integer,
    COUNT(*) FILTER (WHERE outcome = 'client_error')::integer,
    COUNT(*) FILTER (WHERE outcome = 'server_error')::integer,
    ROUND(AVG(duration_ms))::integer
  FROM public.parent_activity_events WHERE occurred_at < date_trunc('day', now())
  GROUP BY occurred_at::date, feature
  ON CONFLICT (summary_date, source, feature) DO UPDATE SET
    total_count = EXCLUDED.total_count, unique_count = EXCLUDED.unique_count,
    success_count = EXCLUDED.success_count, client_error_count = EXCLUDED.client_error_count,
    server_error_count = EXCLUDED.server_error_count, average_duration_ms = EXCLUDED.average_duration_ms;

  INSERT INTO public.analytics_daily_summaries (summary_date, source, feature, total_count, unique_count)
  SELECT visited_at::date, 'site', feature, COUNT(*)::integer, COUNT(DISTINCT visitor_hash)::integer
  FROM public.site_analytics_events WHERE visited_at < date_trunc('day', now())
  GROUP BY visited_at::date, feature
  ON CONFLICT (summary_date, source, feature) DO UPDATE SET
    total_count = EXCLUDED.total_count, unique_count = EXCLUDED.unique_count;

  DELETE FROM public.parent_activity_events WHERE occurred_at < now() - make_interval(days => raw_days);
  GET DIAGNOSTICS parent_removed = ROW_COUNT;
  DELETE FROM public.site_analytics_events WHERE visited_at < now() - make_interval(days => raw_days);
  GET DIAGNOSTICS site_removed = ROW_COUNT;
  DELETE FROM public.analytics_daily_summaries WHERE summary_date < (current_date - make_interval(months => summary_months))::date;
  UPDATE public.analytics_retention_settings SET last_maintenance_at = now(), updated_at = now() WHERE id = true;
  SELECT COUNT(*) INTO summary_total FROM public.analytics_daily_summaries;
  RETURN QUERY SELECT parent_removed, site_removed, summary_total;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION public.rollup_and_prune_admin_analytics() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.rollup_and_prune_admin_analytics() FROM anon;
REVOKE ALL ON FUNCTION public.rollup_and_prune_admin_analytics() FROM authenticated;
GRANT EXECUTE ON FUNCTION public.rollup_and_prune_admin_analytics() TO service_role;

ALTER TABLE public.parent_activity_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_analytics_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_retention_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_daily_summaries ENABLE ROW LEVEL SECURITY;

-- These tables deliberately have no browser-client policies. Only protected
-- server routes using the service role can read or write administrator data.
