-- Privacy-conscious AI usage and estimated-cost reporting for administrators.
-- Prompts, responses, child details, and other family-entered content are never stored.

CREATE TABLE IF NOT EXISTS public.ai_usage_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  feature TEXT NOT NULL,
  model TEXT NOT NULL,
  request_kind TEXT NOT NULL CHECK (request_kind IN ('text', 'image')),
  status TEXT NOT NULL CHECK (status IN ('success', 'failed')),
  input_tokens INTEGER NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
  output_tokens INTEGER NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
  estimated_cost_usd NUMERIC(12, 8) NOT NULL DEFAULT 0 CHECK (estimated_cost_usd >= 0),
  pricing_note TEXT NOT NULL DEFAULT 'Estimated standard paid-tier list price; actual billing may differ or be covered by a free tier.',
  occurred_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS ai_usage_events_date_idx
  ON public.ai_usage_events(occurred_at DESC);
CREATE INDEX IF NOT EXISTS ai_usage_events_feature_date_idx
  ON public.ai_usage_events(feature, occurred_at DESC);
CREATE INDEX IF NOT EXISTS ai_usage_events_model_date_idx
  ON public.ai_usage_events(model, occurred_at DESC);

ALTER TABLE public.ai_usage_events ENABLE ROW LEVEL SECURITY;

-- Browser clients receive no policy. Protected server routes using the service
-- role write and aggregate these records for approved administrators.
