-- Keep each parent's current Parent Assistant conversation until the next
-- 7:00 AM boundary in their timezone. Safe to run repeatedly.

CREATE TABLE IF NOT EXISTS public.parent_ai_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  usage_date DATE NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content TEXT NOT NULL CHECK (length(content) BETWEEN 1 AND 4000),
  source_question TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS parent_ai_messages_user_day_idx
  ON public.parent_ai_messages(user_id, usage_date, created_at, id);

ALTER TABLE public.parent_ai_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Parents can view their current assistant history" ON public.parent_ai_messages;
DROP POLICY IF EXISTS "Parents can create their assistant history" ON public.parent_ai_messages;
DROP POLICY IF EXISTS "Parents can clear their assistant history" ON public.parent_ai_messages;
CREATE POLICY "Parents can view their current assistant history"
  ON public.parent_ai_messages FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Parents can create their assistant history"
  ON public.parent_ai_messages FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Parents can clear their assistant history"
  ON public.parent_ai_messages FOR DELETE USING (auth.uid() = user_id);

DROP FUNCTION IF EXISTS public.consume_parent_ai_question();
CREATE OR REPLACE FUNCTION public.consume_parent_ai_question(timezone_param TEXT DEFAULT 'America/New_York')
RETURNS TABLE (
  allowed BOOLEAN,
  used INTEGER,
  remaining INTEGER,
  daily_limit INTEGER,
  resets_at TIMESTAMP WITH TIME ZONE,
  usage_date DATE
) AS $$
DECLARE
  requesting_user UUID := auth.uid();
  safe_timezone TEXT := COALESCE(NULLIF(btrim(timezone_param), ''), 'America/New_York');
  local_now TIMESTAMP WITHOUT TIME ZONE;
  current_day DATE;
  current_count INTEGER;
  was_consumed BOOLEAN := false;
  limit_value CONSTANT INTEGER := 30;
BEGIN
  IF requesting_user IS NULL THEN
    RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
  END IF;

  BEGIN
    local_now := timezone(safe_timezone, now());
  EXCEPTION WHEN invalid_parameter_value THEN
    safe_timezone := 'America/New_York';
    local_now := timezone(safe_timezone, now());
  END;

  current_day := local_now::date;
  IF local_now::time < TIME '07:00' THEN current_day := current_day - 1; END IF;

  INSERT INTO public.parent_ai_usage (user_id, usage_date, question_count, updated_at)
  VALUES (requesting_user, current_day, 1, timezone('utc'::text, now()))
  ON CONFLICT ON CONSTRAINT parent_ai_usage_pkey DO UPDATE
    SET question_count = public.parent_ai_usage.question_count + 1,
        updated_at = timezone('utc'::text, now())
    WHERE public.parent_ai_usage.question_count < limit_value
  RETURNING question_count INTO current_count;

  IF current_count IS NOT NULL THEN
    was_consumed := true;
  ELSE
    SELECT question_count INTO current_count
    FROM public.parent_ai_usage
    WHERE user_id = requesting_user AND parent_ai_usage.usage_date = current_day;
  END IF;

  RETURN QUERY SELECT
    was_consumed,
    COALESCE(current_count, 0),
    GREATEST(limit_value - COALESCE(current_count, 0), 0),
    limit_value,
    ((current_day + 1)::date + TIME '07:00') AT TIME ZONE safe_timezone,
    current_day;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION public.consume_parent_ai_question(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.consume_parent_ai_question(TEXT) FROM anon;
GRANT EXECUTE ON FUNCTION public.consume_parent_ai_question(TEXT) TO authenticated;
