import { FormEvent, ReactNode, useEffect, useState } from 'react';
import { Link, Navigate, useLocation, useParams } from 'react-router-dom';
import { ExternalLink, Mail, Send, ShieldCheck, X } from 'lucide-react';
import { Button } from '../components/Button';
import { Input } from '../components/Input';
import { Select } from '../components/Select';
import { Textarea } from '../components/Textarea';
import { useAuth } from '../context/AuthContext';
import { apiFetch } from '../utils/api';
import { productFeatures } from '../content/featureRegistry';

type Issue = Record<string, any> & { id:string; issue_date:string; title:string; introduction:string; parent_tips:string[] };
const displayDate=(value:string)=>new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`)).replace(/^(\d{2}) ([A-Za-z]{3}) /,(_match,day,month)=>`${Number.parseInt(day,10)} ${month}, `);
const featureIdFor=(item:any)=>item.id||productFeatures.find(feature=>feature.title===item.title)?.id;

export default function Newsletter(){
  const {month,issueDate}=useParams<{month?:string;issueDate?:string}>();
  const routeLocation=useLocation();
  const {user}=useAuth();
  const [email,setEmail]=useState(''); const [issues,setIssues]=useState<Issue[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false);
  const [message,setMessage]=useState<{ok:boolean;text:string}|null>(null);
  const [post,setPost]=useState({contributionType:'story',title:'',content:'',displayName:'',sourceUrl:'',consentToPublish:false});
  useEffect(()=>{
    const query=new URLSearchParams(routeLocation.search);
    if(query.get('confirmation')) setMessage({ok:query.get('confirmation')==='success',text:query.get('confirmation')==='success'?'Subscription confirmed. The next weekly issue will arrive on its scheduled delivery day.':'That confirmation link is invalid or already used.'});
    if(query.get('unsubscribe')) setMessage({ok:query.get('unsubscribe')==='success',text:query.get('unsubscribe')==='success'?'You have been unsubscribed.':'That unsubscribe link is invalid.'});
    fetch('/api/newsletters').then(response=>response.ok?response.json():Promise.reject()).then(data=>setIssues(Array.isArray(data)?data:[])).catch(()=>setMessage({ok:false,text:'The newsletter archive is temporarily unavailable.'})).finally(()=>setLoading(false));
  },[routeLocation.search]);
  const subscribe=async(event:FormEvent)=>{event.preventDefault();setBusy(true);try{const response=await fetch('/api/newsletter/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const data=await response.json();if(!response.ok)throw new Error(data.error);setMessage({ok:true,text:data.message});setEmail('');}catch(error){setMessage({ok:false,text:error instanceof Error?error.message:'Subscription failed.'});}finally{setBusy(false);}};
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);try{const response=await apiFetch('/api/newsletter/community-submissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(post)},0);const data=await response.json();if(!response.ok)throw new Error(data.error);setMessage({ok:true,text:data.message});setPost({...post,title:'',content:'',sourceUrl:'',consentToPublish:false});}catch(error){setMessage({ok:false,text:error instanceof Error?error.message:'Submission failed.'});}finally{setBusy(false);}};
  const monthGroups=issues.reduce<Record<string,Issue[]>>((groups,issue)=>{const key=issue.issue_date.slice(0,7);(groups[key]||=[]).push(issue);return groups;},{});
  const monthKeys=Object.keys(monthGroups).sort((a,b)=>b.localeCompare(a));
  const monthLabel=(value:string)=>new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}-01T12:00:00Z`));
  const selectedIssue=issueDate?issues.find(issue=>issue.issue_date===issueDate):undefined;
  const isSubscribePage=routeLocation.pathname==='/newsletter/subscribe';
  const isCommunityPage=routeLocation.pathname==='/newsletter/community';
  const closeIssueTab=()=>{
    if(!issueDate)return;
    const monthUrl=`/newsletter/archive/${issueDate.slice(0,7)}`;
    window.close();
    window.setTimeout(()=>{if(!window.closed)window.location.assign(monthUrl);},100);
  };

  if(isSubscribePage)return <div className="page-shell"><div className="page-container flex min-h-[70vh] items-center justify-center"><section className="surface w-full max-w-3xl p-7 sm:p-10"><h1 className="text-3xl font-black sm:text-4xl">Get the weekly issue</h1><p className="mt-3 text-slate-600">Confirm once by email. Every issue includes one-click unsubscribe.</p>{message&&<div role="status" className={`mt-5 rounded-xl border p-4 text-sm font-bold ${message.ok?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-red-200 bg-red-50 text-red-800'}`}>{message.text}</div>}<form onSubmit={subscribe} className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-end"><Input label="Email address" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><Button disabled={busy}><Mail className="mr-2 h-4 w-4"/>Subscribe</Button></form><p className="mt-5 flex gap-2 text-sm text-slate-500"><ShieldCheck className="h-5 w-5 text-emerald-600"/>Subscriber addresses stay private.</p></section></div></div>;

  if(isCommunityPage)return <div className="page-shell"><div className="page-container flex min-h-[70vh] items-center justify-center">{message&&<div role="status" className={`fixed top-24 z-20 rounded-xl border p-4 text-sm font-bold ${message.ok?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-red-200 bg-red-50 text-red-800'}`}>{message.text}</div>}<CommunitySubmission user={user} post={post} setPost={setPost} submit={submit} busy={busy}/></div></div>;

  if(issueDate)return <div className="page-shell"><div className="page-container space-y-6"><button type="button" onClick={closeIssueTab} className="inline-flex items-center gap-2 font-bold text-brand-700"><X className="h-4 w-4"/>Close newsletter</button>{loading?<p className="surface p-8">Loading…</p>:selectedIssue?<IssueCard issue={selectedIssue}/>:<p className="surface p-8 text-slate-600">This newsletter issue is unavailable.</p>}</div></div>;

  if(month)return <div className="page-shell"><div className="page-container space-y-7"><section className="public-hero p-7 sm:p-10"><p className="text-xs font-black uppercase tracking-widest text-brand-700">Weekly archive</p><h1 className="mt-2 text-4xl font-black">{monthLabel(month)}</h1><p className="mt-3 text-slate-600">Select an issue below. Each newsletter opens in a new browser tab so this monthly list remains available.</p></section>{loading?<p className="surface p-8">Loading…</p>:!monthGroups[month]?.length?<p className="surface p-8 text-slate-600">No published newsletters are available for this month.</p>:<div className="surface divide-y divide-slate-200 px-6">{monthGroups[month].map(issue=><Link key={issue.id} to={`/newsletter/issues/${issue.issue_date}`} target="_blank" rel="noopener noreferrer" className="flex items-center justify-between gap-4 py-5 font-bold text-slate-800 hover:text-brand-700"><span><span className="block text-xs uppercase tracking-wider text-brand-600">{displayDate(issue.issue_date)}</span><span className="mt-1 block text-lg">{issue.title}</span></span><ExternalLink className="h-5 w-5 shrink-0"/></Link>)}</div>}</div></div>;

  if(routeLocation.pathname==='/newsletter')return loading?<div className="page-shell"><div className="page-container"><p className="surface p-8">Loading the latest newsletter…</p></div></div>:monthKeys.length?<Navigate to={`/newsletter/archive/${monthKeys[0]}`} replace/>:<div className="page-shell"><div className="page-container"><p className="surface p-8 text-slate-600">The first issue will appear after its scheduled publication.</p></div></div>;

  return null;
}

function CommunitySubmission({user,post,setPost,submit,busy}:{user:any;post:any;setPost:(value:any)=>void;submit:(event:FormEvent)=>Promise<void>;busy:boolean}){return <section className="surface w-full max-w-4xl p-7 sm:p-10"><h1 className="text-3xl font-black sm:text-4xl">Share with the community</h1><p className="mt-3 text-sm leading-7 text-slate-600">Signed-in parents may submit autism-related stories, news, information, tips, testimonials, or mission-aligned advertisements. Everything is reviewed before publication. Content must be non-medical and non-clinical, and must never include identifying information about an autistic person.</p>{user?<form onSubmit={submit} className="mt-6 grid gap-4 md:grid-cols-2"><Select label="Type" value={post.contributionType} onChange={e=>setPost({...post,contributionType:e.target.value})}>{['story','news','information','tip','testimonial','advertisement'].map(type=><option key={type}>{type}</option>)}</Select><Input label="Public display name or advertiser" value={post.displayName} onChange={e=>setPost({...post,displayName:e.target.value})} placeholder="First name, initials, organization, or Visual Steps parent" required/><Input label="Title" value={post.title} onChange={e=>setPost({...post,title:e.target.value})} required className="md:col-span-2"/><Input label="Source or destination link (required for news and ads)" type="url" value={post.sourceUrl} onChange={e=>setPost({...post,sourceUrl:e.target.value})} className="md:col-span-2"/><Textarea label="Content" rows={7} value={post.content} onChange={e=>setPost({...post,content:e.target.value})} required className="md:col-span-2"/><label className="flex gap-3 text-sm md:col-span-2"><input type="checkbox" checked={post.consentToPublish} onChange={e=>setPost({...post,consentToPublish:e.target.checked})} required/><span>I created or may share this content and permit Visual Steps to review, edit for clarity, and publish it.</span></label><Button disabled={busy}><Send className="mr-2 h-4 w-4"/>Submit for review</Button></form>:<p className="mt-6 rounded-xl bg-brand-50 p-4 text-sm">Sign in as a parent to submit content. Reading remains public. Organizations may also <Link to="/contact" className="font-bold underline">contact Visual Steps</Link> about a mission-aligned advertisement.</p>}</section>}

export function IssueCard({issue}:{issue:Issue}){
  const title=(key:string,fallback:string)=>issue.section_titles?.[key]||fallback;
  const visible=(key:string)=>issue.section_visibility?.[key]!==false;
  return <article className="newsletter-copy surface p-6 sm:p-8"><p className="text-xs font-black uppercase text-brand-700">{displayDate(issue.issue_date)}</p><h3 className="mt-2 text-2xl font-black">{issue.title}</h3><p className="mt-3 text-slate-600">{issue.introduction}</p><div className="mt-6 grid gap-5 lg:grid-cols-2">
    {visible('feature_previews')&&<Section fullWidth tone="violet" title={title('feature_previews','Feature Previews')} items={(issue.feature_previews||[]).map((x:any)=>{
      const featureId=featureIdFor(x);
      return <><img src={x.imageUrl} alt={`${x.title} feature preview`} className="mb-3 h-52 w-full rounded-xl object-contain object-top sm:h-64"/><b>{x.title}</b> — {x.caption}{x.familyImpact&&<span className="mt-2 block"><b>Why it matters:</b> {x.familyImpact}</span>}{featureId&&<Link to={`/features/${featureId}`} target="_blank" rel="noopener noreferrer" className="mt-3 inline-flex font-bold text-brand-800 underline underline-offset-4">Read more</Link>}</>;
    })}/>} {visible('new_features')&&<Section fullWidth itemColumns={2} tone="blue" title={title('new_features','Newly Added Feature Details')} items={(issue.new_features||[]).map((x:any)=>{
      const featureId=featureIdFor(x);
      return <><b className="text-slate-900">{x.title}</b><span className="mt-1 block">{x.summary}</span><span className="mt-2 block">{x.details}</span>{x.familyImpact&&<span className="mt-2 block"><b>How this supports growth:</b> {x.familyImpact}</span>}<small className="mt-2 block font-semibold text-brand-800">Where to find it: {x.help}</small>{featureId&&<Link to={`/features/${featureId}`} target="_blank" rel="noopener noreferrer" className="mt-3 inline-flex font-bold text-brand-800 underline underline-offset-4">Read more</Link>}</>;
    })}/>} {visible('community_posts')&&<Section tone="amber" title={title('community_posts','Parent Stories, News, Information, Tips and Tricks')} items={(issue.community_posts||[]).map((x:any)=><><b>{x.title}</b> ({x.type}) — {x.content} — {x.displayName}{x.sourceUrl&&<a href={x.sourceUrl} target="_blank" rel="noreferrer" className="ml-1 underline">Source</a>}{x.editorialContext&&<small className="mt-2 block italic">{x.editorialContext}</small>}</>)}/>} {visible('parent_testimonials')&&<Section tone="rose" title={title('parent_testimonials','Parent Testimonials')} items={(issue.parent_testimonials||[]).map((x:any)=><>“{x.quote}” — <b>{x.displayName}</b>{x.editorialContext&&<small className="mt-2 block italic">{x.editorialContext}</small>}</>)}/>}
    {visible('popular_features')&&<Section tone="emerald" title={title('popular_features','Most Popular Features')} items={(issue.popular_features||[]).map((x:any)=><><b>{x.title}</b> — {x.explanation}</>)}/>}
    {visible('recommended_resources')&&<Section tone="cyan" title={title('recommended_resources','Suggested Activities, Games and Websites')} items={(issue.recommended_resources||[]).map((x:any)=><><b>{x.title}</b> ({x.type}) — {x.description}{x.url&&<a href={x.url} target="_blank" rel="noreferrer" className="ml-1 underline">Visit</a>}</>)}/>}
    {visible('suggested_books_resources')&&<Section fullWidth itemColumns={2} tone="amber" title={title('suggested_books_resources','Suggested Books and Resources')} items={(issue.suggested_books_resources||[]).map((x:any)=><><b>{x.title}</b> ({x.type}){x.creator&&<> by {x.creator}</>} — {x.description}{x.url&&<a href={x.url} target="_blank" rel="noreferrer" className="ml-1 underline">Visit resource</a>}</>)}/>}
    {visible('advertisements')&&<Section fullWidth itemColumns={2} tone="orange" title={title('advertisements','Mission-Aligned Advertisements')} items={(issue.advertisements||[]).map((x:any)=><><span className="text-xs font-black uppercase tracking-wider text-amber-800">Advertisement</span><span className="mt-1 block"><b>{x.title}</b> — {x.description}</span><span className="mt-2 block text-xs">From {x.advertiser}. {x.disclosure}</span>{x.destinationUrl&&<a href={x.destinationUrl} target="_blank" rel="sponsored noreferrer" className="mt-2 inline-block font-bold underline">Visit advertiser</a>}</>)}/>}
    {visible('parent_tips')&&<Section bulleted tone="lime" title={title('parent_tips','Tips and Tricks for Parents')} items={issue.parent_tips||[]}/>}
    {visible('membership_details')&&<Section tone="indigo" title={title('membership_details','Current Visual Steps Membership Details')} items={(issue.membership_details||[]).map((x:any)=><><b>{x.name}: {x.price}</b> — {x.status}. {x.details}</>)}/>}
  </div><NewsletterLinks links={issue.footer_links}/></article>;
}
function NewsletterLinks({links}:{links?:Record<string,string>}){const items=[['Subscribe Newsletter','/newsletter/subscribe'],['Facebook',links?.facebook],['Instagram',links?.instagram]].filter((item):item is [string,string]=>Boolean(item[1]));return <nav aria-label="Newsletter links" className="mt-7 flex flex-wrap gap-x-5 gap-y-2 border-t border-slate-200 pt-5 text-sm font-bold text-brand-800">{items.map(([label,url])=><a key={label} href={url} target="_blank" rel="noopener noreferrer" className="underline underline-offset-4">{label}</a>)}</nav>}
function Section({title,items,tone,fullWidth=false,itemColumns=1,bulleted=false}:{title:string;items:ReactNode[];tone:'blue'|'violet'|'amber'|'orange'|'rose'|'emerald'|'cyan'|'indigo'|'lime';fullWidth?:boolean;itemColumns?:1|2;bulleted?:boolean}){if(!items.length)return null;const colors={blue:'border-blue-200 bg-blue-50/80',violet:'border-violet-200 bg-violet-50/80',amber:'border-amber-200 bg-amber-50/80',orange:'border-orange-200 bg-orange-50/80',rose:'border-rose-200 bg-rose-50/80',emerald:'border-emerald-200 bg-emerald-50/80',cyan:'border-cyan-200 bg-cyan-50/80',indigo:'border-indigo-200 bg-indigo-50/80',lime:'border-lime-200 bg-lime-50/80'};return <section className={`rounded-2xl border p-5 ${fullWidth?'lg:col-span-2':''} ${colors[tone]}`}><h4 className="font-black text-slate-900">{title}</h4><ul className={`mt-3 grid gap-4 text-sm leading-6 text-slate-700 ${itemColumns===2?'md:grid-cols-2':''} ${bulleted?'list-outside list-disc pl-5 marker:text-lime-700':''}`}>{items.map((item,index)=><li key={index} className={itemColumns===2?'rounded-xl border border-blue-100 bg-white/70 p-4':''}>{item}</li>)}</ul></section>}
